[package]
name = "blessed-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.8"
fxhash = "0.2.1"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tera = "1.15"
tokio = { version = "1.17", features = ["full"] }
tower-http = { version = "0.2.5", features = ["fs", "trace"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
